CREATE TABLE LIVRO
	(ISBN INTEGER,
	titulo VARCHAR (50),
	CONSTRAINT pk_livro PRIMARY KEY (isbn)
	);

DROP TABLE LIVRO;

ALTER TABLE livro DROP CONSTRAINT livro_pkey;
ALTER TABLE livro ADD CONSTRAINT pk_livro PRIMARY KEY (isbn);


SELECT * FROM livro;
