-- Usuário B

begin;
SELECT * FROM conta;
INSERT INTO CONTA VALUES (7, 'Gabriel', 2000);
SELECT * FROM CONTA;
commit;

begin;
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SELECT * FROM CONTA;
end;

SELECT * FROM CONTA;


-- SELECT FOR UPDATE
begin;
SELECT * FROM CONTA FOR UPDATE;
UPDATE CONTA SET saldo = 1000 WHERE id = 4;
SELECT * FROM CONTA;
commit;